# SPDX-FileCopyrightText: Copyright Christian Ams√ºss <chrysn@fsfe.org>, Silano Systems
# SPDX-License-Identifier: MIT OR Apache-2.0

include = "../build/imports/ariel-os/ariel-os-cargo.toml"

[unstable]
# This is needed so the "include" statement above works.
config-include = true
